language: csharp
solution: ./SampleWebAPI.sln

env:
  - AZURE_WA_USERNAME=ci-user-1 AZURE_WA_PASSWORD=PrecisionLender1 AZURE_WA_SITE=precisionlender-simplewebapi

install:
  - sudo apt-get install nunit-console
  - nuget restore ./SampleWebAPI.sln

script:
  - xbuild ./SampleWebAPI.sln
  - nunit-console ./SampleWebAPITests/bin/Debug/SampleWebAPITests.dll

deploy:
  - provider: azure_web_apps
  - username: "ci-user-1"
  - password: "PrecisionLender1"
  - site: "precisionlender-simplewebapi"
