language: csharp
solution: ./SampleWebAPI.sln

install:
  - sudo apt-get install nunit-console
  - nuget restore ./SampleWebAPI.sln

script:
  - xbuild ./SampleWebAPI.sln
  - nunit-console ./SampleWebAPITests/bin/Debug/SampleWebAPITests.dll

deploy:
  - provider: azure_web_apps
  - username: ci-user-1
  - password: PrecisionLender1
  - site: precisionlender-simplewebapi
