language: csharp
solution: ./SampleWebAPI.sln

install:
  - sudo apt-get install nunit-console
  - sudo apt-get install npm
  - sudo npm install -g azure-cli
  - nuget restore ./SampleWebAPI.sln

script:
  - xbuild ./SampleWebAPI.sln
  - nunit-console ./SampleWebAPITests/bin/Debug/SampleWebAPITests.dll
